[package]
name = "htmx"
version = "0.1.0"
edition = "2024"

[dependencies]
askama = { version = "0.13.0" }
askama_axum = "0.4.0"
axum = "0.8.3"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0.219", features = ["derive"] }
tracing-subscriber = "0.3"